#!/usr/bin/python3

import os
import sys
import gi
gi.require_version('Gtk', '3.0')
from gi.repository import GLib 

os.execvp(GLib.get_user_data_dir() + "/cinnamon/extensions/CinnamonBurnMyWindows@klangman/CinnamonBurnMyWindowsTest.py", (" ",) + tuple(sys.argv[1:]))
